name: river-levels
channels: 
 - conda-forge
dependencies:
  - python=3.9
  - streamlit
  - pandas
  - numpy
  - requests
  - pip
  - altair
  - pydeck
  - pre-commit
  - pip
  - pip:
    - -e .
    - dvc[s3]